import type { User, Appointment, LoginResponse, ApiResponse } from '@/types'

// ─── Helpers ────────────────────────────────────────────────────────────────

const today = new Date()
today.setHours(0, 0, 0, 0)

const makeDate = (dayOffset: number, hour: number, minute: number): string => {
  const d = new Date(today)
  d.setDate(d.getDate() + dayOffset)
  d.setHours(hour, minute, 0, 0)
  return d.toISOString()
}

const makeDateOnly = (dayOffset: number): string => {
  const d = new Date(today)
  d.setDate(d.getDate() + dayOffset)
  return d.toISOString().split('T')[0]!
}

export const simulateDelay = (ms = 300): Promise<void> =>
  new Promise(resolve => setTimeout(resolve, ms))

// ─── Users ──────────────────────────────────────────────────────────────────

export const mockUsers: User[] = [
  // Admin
  {
    userId: 'admin-001',
    email: 'admin@clinicalatelier.com',
    firstName: 'Carlos',
    lastName: 'Rodríguez',
    role: 'ADMIN',
    isActive: true,
    phone: '+54 11 5555-0100',
    createdAt: '2024-01-15T08:00:00Z',
    updatedAt: '2024-06-01T10:00:00Z',
  },
  // Dentists
  {
    userId: 'dent-001',
    email: 'maria.garcia@clinicalatelier.com',
    firstName: 'María',
    lastName: 'García',
    role: 'DENTIST',
    isActive: true,
    phone: '+54 11 5555-0101',
    createdAt: '2024-01-20T08:00:00Z',
    updatedAt: '2024-06-01T10:00:00Z',
  },
  {
    userId: 'dent-002',
    email: 'juan.perez@clinicalatelier.com',
    firstName: 'Juan',
    lastName: 'Pérez',
    role: 'DENTIST',
    isActive: true,
    phone: '+54 11 5555-0102',
    birthDate: '1980-05-15',
    createdAt: '2024-02-10T08:00:00Z',
    updatedAt: '2024-06-01T10:00:00Z',
  },
  {
    userId: 'dent-003',
    email: 'ana.martinez@clinicalatelier.com',
    firstName: 'Ana',
    lastName: 'Martínez',
    role: 'DENTIST',
    isActive: false,
    phone: '+54 11 5555-0103',
    createdAt: '2024-03-01T08:00:00Z',
    updatedAt: '2024-05-15T10:00:00Z',
  },
  // Assistants
  {
    userId: 'asst-001',
    email: 'laura.diaz@clinicalatelier.com',
    firstName: 'Laura',
    lastName: 'Díaz',
    role: 'ASSISTANT',
    isActive: true,
    phone: '+54 11 5555-0104',
    createdAt: '2024-01-25T08:00:00Z',
    updatedAt: '2024-06-01T10:00:00Z',
  },
  {
    userId: 'asst-002',
    email: 'pedro.lopez@clinicalatelier.com',
    firstName: 'Pedro',
    lastName: 'López',
    role: 'ASSISTANT',
    isActive: true,
    phone: '+54 11 5555-0105',
    createdAt: '2024-02-15T08:00:00Z',
    updatedAt: '2024-06-01T10:00:00Z',
  },
  // Patients
  {
    userId: 'pat-001',
    email: 'sofia.torres@gmail.com',
    firstName: 'Sofía',
    lastName: 'Torres',
    role: 'PATIENT',
    isActive: true,
    phone: '+54 11 5555-0201',
    birthDate: '1990-03-12',
    address: 'Av. Corrientes 1234, CABA',
    gender: 'Female',
    createdAt: '2024-02-01T08:00:00Z',
    updatedAt: '2024-06-01T10:00:00Z',
  },
  {
    userId: 'pat-002',
    email: 'martin.fernandez@gmail.com',
    firstName: 'Martín',
    lastName: 'Fernández',
    role: 'PATIENT',
    isActive: true,
    phone: '+54 11 5555-0202',
    birthDate: '1985-07-22',
    address: 'Calle Florida 567, CABA',
    gender: 'Male',
    createdAt: '2024-02-05T08:00:00Z',
    updatedAt: '2024-06-01T10:00:00Z',
  },
  {
    userId: 'pat-003',
    email: 'lucia.gimenez@gmail.com',
    firstName: 'Lucía',
    lastName: 'Giménez',
    role: 'PATIENT',
    isActive: true,
    phone: '+54 11 5555-0203',
    birthDate: '1995-11-08',
    address: 'Av. Santa Fe 890, CABA',
    gender: 'Female',
    createdAt: '2024-02-10T08:00:00Z',
    updatedAt: '2024-06-01T10:00:00Z',
  },
  {
    userId: 'pat-004',
    email: 'roberto.castro@gmail.com',
    firstName: 'Roberto',
    lastName: 'Castro',
    role: 'PATIENT',
    isActive: true,
    phone: '+54 11 5555-0204',
    birthDate: '1978-09-30',
    address: 'Av. Rivadavia 3456, CABA',
    gender: 'Male',
    createdAt: '2024-02-15T08:00:00Z',
    updatedAt: '2024-06-01T10:00:00Z',
  },
  {
    userId: 'pat-005',
    email: 'valentina.rios@gmail.com',
    firstName: 'Valentina',
    lastName: 'Ríos',
    role: 'PATIENT',
    isActive: true,
    phone: '+54 11 5555-0205',
    birthDate: '2000-01-15',
    address: 'Calle Lavalle 234, CABA',
    gender: 'Female',
    createdAt: '2024-03-01T08:00:00Z',
    updatedAt: '2024-06-01T10:00:00Z',
  },
  {
    userId: 'pat-006',
    email: 'diego.mendoza@gmail.com',
    firstName: 'Diego',
    lastName: 'Mendoza',
    role: 'PATIENT',
    isActive: true,
    phone: '+54 11 5555-0206',
    birthDate: '1982-06-18',
    address: 'Av. Belgrano 789, CABA',
    gender: 'Male',
    createdAt: '2024-03-05T08:00:00Z',
    updatedAt: '2024-06-01T10:00:00Z',
  },
  {
    userId: 'pat-007',
    email: 'carla.silva@gmail.com',
    firstName: 'Carla',
    lastName: 'Silva',
    role: 'PATIENT',
    isActive: false,
    phone: '+54 11 5555-0207',
    birthDate: '1992-04-25',
    address: 'Calle Callao 456, CABA',
    gender: 'Female',
    createdAt: '2024-03-10T08:00:00Z',
    updatedAt: '2024-05-20T10:00:00Z',
  },
  {
    userId: 'pat-008',
    email: 'pablo.aguirre@gmail.com',
    firstName: 'Pablo',
    lastName: 'Aguirre',
    role: 'PATIENT',
    isActive: true,
    phone: '+54 11 5555-0208',
    birthDate: '1988-08-14',
    address: 'Av. Alem 123, CABA',
    gender: 'Male',
    createdAt: '2024-03-15T08:00:00Z',
    updatedAt: '2024-06-01T10:00:00Z',
  },
  {
    userId: 'pat-009',
    email: 'florencia.molinari@gmail.com',
    firstName: 'Florencia',
    lastName: 'Molinari',
    role: 'PATIENT',
    isActive: true,
    phone: '+54 11 5555-0209',
    birthDate: '1998-12-03',
    address: 'Calle Uruguay 567, CABA',
    gender: 'Female',
    createdAt: '2024-04-01T08:00:00Z',
    updatedAt: '2024-06-01T10:00:00Z',
  },
  {
    userId: 'pat-010',
    email: 'gustavo.medina@gmail.com',
    firstName: 'Gustavo',
    lastName: 'Medina',
    role: 'PATIENT',
    isActive: true,
    phone: '+54 11 5555-0210',
    birthDate: '1975-10-20',
    address: 'Av. Córdoba 2345, CABA',
    gender: 'Male',
    createdAt: '2024-04-10T08:00:00Z',
    updatedAt: '2024-06-01T10:00:00Z',
  },
  {
    userId: 'pat-011',
    email: 'nicolas.romero@gmail.com',
    firstName: 'Nicolás',
    lastName: 'Romero',
    role: 'PATIENT',
    isActive: true,
    phone: '+54 11 5555-0211',
    birthDate: '1993-02-28',
    address: 'Calle Paraná 890, CABA',
    gender: 'Male',
    createdAt: '2024-04-15T08:00:00Z',
    updatedAt: '2024-06-01T10:00:00Z',
  },
]

// ─── Appointments ───────────────────────────────────────────────────────────

export const mockAppointments: Appointment[] = [
  // Today - Scheduled
  {
    appointmentId: 'apt-001',
    tenantId: 'tenant-001',
    patientId: 'pat-001',
    patientName: 'Sofía Torres',
    dentistId: 'dent-001',
    dentistName: 'María García',
    appointmentTime: makeDate(0, 9, 0),
    durationMinutes: 30,
    status: 'SCHEDULED',
    notes: 'Limpieza dental de rutina',
    reminderSentAt: makeDate(-1, 10, 0),
    reminderAttempts: 1,
    createdAt: makeDate(-7, 8, 0),
    updatedAt: makeDate(-1, 10, 0),
  },
  {
    appointmentId: 'apt-002',
    tenantId: 'tenant-001',
    patientId: 'pat-003',
    patientName: 'Lucía Giménez',
    dentistId: 'dent-001',
    dentistName: 'María García',
    appointmentTime: makeDate(0, 10, 0),
    durationMinutes: 45,
    status: 'SCHEDULED',
    notes: 'Consulta por dolor molar',
    reminderSentAt: makeDate(-1, 10, 0),
    reminderAttempts: 1,
    createdAt: makeDate(-5, 8, 0),
    updatedAt: makeDate(-1, 10, 0),
  },
  {
    appointmentId: 'apt-003',
    tenantId: 'tenant-001',
    patientId: 'pat-005',
    patientName: 'Valentina Ríos',
    dentistId: 'dent-002',
    dentistName: 'Juan Pérez',
    appointmentTime: makeDate(0, 11, 0),
    durationMinutes: 30,
    status: 'SCHEDULED',
    notes: 'Control de ortodoncia',
    createdAt: makeDate(-3, 8, 0),
    updatedAt: makeDate(-3, 8, 0),
    reminderAttempts: 0,
  },
  {
    appointmentId: 'apt-004',
    tenantId: 'tenant-001',
    patientId: 'pat-008',
    patientName: 'Pablo Aguirre',
    dentistId: 'dent-002',
    dentistName: 'Juan Pérez',
    appointmentTime: makeDate(0, 14, 0),
    durationMinutes: 60,
    status: 'SCHEDULED',
    notes: 'Endodoncia conducto superior derecho',
    createdAt: makeDate(-10, 8, 0),
    updatedAt: makeDate(-10, 8, 0),
    reminderAttempts: 0,
  },
  {
    appointmentId: 'apt-005',
    tenantId: 'tenant-001',
    patientId: 'pat-010',
    patientName: 'Gustavo Medina',
    dentistId: 'dent-001',
    dentistName: 'María García',
    appointmentTime: makeDate(0, 15, 30),
    durationMinutes: 30,
    status: 'SCHEDULED',
    notes: 'Revisión general',
    createdAt: makeDate(-2, 8, 0),
    updatedAt: makeDate(-2, 8, 0),
    reminderAttempts: 0,
  },
  // Today - Completed
  {
    appointmentId: 'apt-006',
    tenantId: 'tenant-001',
    patientId: 'pat-002',
    patientName: 'Martín Fernández',
    dentistId: 'dent-001',
    dentistName: 'María García',
    appointmentTime: makeDate(0, 8, 0),
    durationMinutes: 30,
    status: 'COMPLETED',
    notes: 'Limpieza dental',
    createdAt: makeDate(-7, 8, 0),
    updatedAt: makeDate(0, 8, 30),
    reminderAttempts: 0,
  },
  // Tomorrow - Scheduled
  {
    appointmentId: 'apt-007',
    tenantId: 'tenant-001',
    patientId: 'pat-004',
    patientName: 'Roberto Castro',
    dentistId: 'dent-001',
    dentistName: 'María García',
    appointmentTime: makeDate(1, 9, 0),
    durationMinutes: 30,
    status: 'SCHEDULED',
    notes: 'Dolor de muela',
    createdAt: makeDate(-4, 8, 0),
    updatedAt: makeDate(-4, 8, 0),
    reminderAttempts: 0,
  },
  {
    appointmentId: 'apt-008',
    tenantId: 'tenant-001',
    patientId: 'pat-006',
    patientName: 'Diego Mendoza',
    dentistId: 'dent-002',
    dentistName: 'Juan Pérez',
    appointmentTime: makeDate(1, 10, 30),
    durationMinutes: 45,
    status: 'SCHEDULED',
    notes: 'Caries en molar inferior',
    createdAt: makeDate(-3, 8, 0),
    updatedAt: makeDate(-3, 8, 0),
    reminderAttempts: 0,
  },
  {
    appointmentId: 'apt-009',
    tenantId: 'tenant-001',
    patientId: 'pat-009',
    patientName: 'Florencia Molinari',
    dentistId: 'dent-001',
    dentistName: 'María García',
    appointmentTime: makeDate(1, 14, 0),
    durationMinutes: 30,
    status: 'SCHEDULED',
    notes: 'Blanqueamiento dental',
    createdAt: makeDate(-6, 8, 0),
    updatedAt: makeDate(-6, 8, 0),
    reminderAttempts: 0,
  },
  // Past appointments
  {
    appointmentId: 'apt-010',
    tenantId: 'tenant-001',
    patientId: 'pat-001',
    patientName: 'Sofía Torres',
    dentistId: 'dent-001',
    dentistName: 'María García',
    appointmentTime: makeDate(-5, 10, 0),
    durationMinutes: 30,
    status: 'COMPLETED',
    notes: 'Revisión general - todo ok',
    createdAt: makeDate(-12, 8, 0),
    updatedAt: makeDate(-5, 10, 30),
    reminderAttempts: 1,
  },
  {
    appointmentId: 'apt-011',
    tenantId: 'tenant-001',
    patientId: 'pat-005',
    patientName: 'Valentina Ríos',
    dentistId: 'dent-002',
    dentistName: 'Juan Pérez',
    appointmentTime: makeDate(-6, 11, 0),
    durationMinutes: 30,
    status: 'COMPLETED',
    notes: 'Cambio de brackets',
    createdAt: makeDate(-20, 8, 0),
    updatedAt: makeDate(-6, 11, 30),
    reminderAttempts: 1,
  },
  {
    appointmentId: 'apt-012',
    tenantId: 'tenant-001',
    patientId: 'pat-007',
    patientName: 'Carla Silva',
    dentistId: 'dent-001',
    dentistName: 'María García',
    appointmentTime: makeDate(-3, 9, 0),
    durationMinutes: 30,
    status: 'CANCELLED',
    notes: 'Cancelado por paciente - reprogramar',
    createdAt: makeDate(-10, 8, 0),
    updatedAt: makeDate(-4, 16, 0),
    reminderAttempts: 2,
  },
  {
    appointmentId: 'apt-013',
    tenantId: 'tenant-001',
    patientId: 'pat-011',
    patientName: 'Nicolás Romero',
    dentistId: 'dent-002',
    dentistName: 'Juan Pérez',
    appointmentTime: makeDate(-2, 15, 0),
    durationMinutes: 30,
    status: 'NO_SHOW',
    notes: 'Paciente no asistió',
    createdAt: makeDate(-9, 8, 0),
    updatedAt: makeDate(-2, 15, 30),
    reminderAttempts: 3,
  },
  {
    appointmentId: 'apt-014',
    tenantId: 'tenant-001',
    patientId: 'pat-010',
    patientName: 'Gustavo Medina',
    dentistId: 'dent-001',
    dentistName: 'María García',
    appointmentTime: makeDate(-7, 8, 30),
    durationMinutes: 60,
    status: 'COMPLETED',
    notes: 'Extracción de cordal inferior izquierdo - exitosa',
    createdAt: makeDate(-21, 8, 0),
    updatedAt: makeDate(-7, 9, 30),
    reminderAttempts: 1,
  },
  {
    appointmentId: 'apt-015',
    tenantId: 'tenant-001',
    patientId: 'pat-003',
    patientName: 'Lucía Giménez',
    dentistId: 'dent-002',
    dentistName: 'Juan Pérez',
    appointmentTime: makeDate(-4, 16, 0),
    durationMinutes: 30,
    status: 'COMPLETED',
    notes: 'Reparación de corona',
    createdAt: makeDate(-14, 8, 0),
    updatedAt: makeDate(-4, 16, 30),
    reminderAttempts: 1,
  },
  // Next week
  {
    appointmentId: 'apt-016',
    tenantId: 'tenant-001',
    patientId: 'pat-002',
    patientName: 'Martín Fernández',
    dentistId: 'dent-001',
    dentistName: 'María García',
    appointmentTime: makeDate(7, 10, 0),
    durationMinutes: 30,
    status: 'SCHEDULED',
    notes: 'Control post-limpieza',
    createdAt: makeDate(-1, 8, 0),
    updatedAt: makeDate(-1, 8, 0),
    reminderAttempts: 0,
  },
  {
    appointmentId: 'apt-017',
    tenantId: 'tenant-001',
    patientId: 'pat-006',
    patientName: 'Diego Mendoza',
    dentistId: 'dent-001',
    dentistName: 'María García',
    appointmentTime: makeDate(8, 9, 0),
    durationMinutes: 45,
    status: 'SCHEDULED',
    notes: 'Tratamiento de conducto (sesión 2)',
    createdAt: makeDate(-7, 8, 0),
    updatedAt: makeDate(-7, 8, 0),
    reminderAttempts: 0,
  },
  {
    appointmentId: 'apt-018',
    tenantId: 'tenant-001',
    patientId: 'pat-004',
    patientName: 'Roberto Castro',
    dentistId: 'dent-002',
    dentistName: 'Juan Pérez',
    appointmentTime: makeDate(10, 11, 0),
    durationMinutes: 30,
    status: 'SCHEDULED',
    notes: 'Prótesis dental - prueba',
    createdAt: makeDate(-5, 8, 0),
    updatedAt: makeDate(-5, 8, 0),
    reminderAttempts: 0,
  },
]

// ─── Filter helpers ─────────────────────────────────────────────────────────

export const filterAppointmentsByDateRange = (
  start: string,
  end: string,
): Appointment[] => {
  const startDate = new Date(start)
  const endDate = new Date(end)
  return mockAppointments.filter(a => {
    const date = new Date(a.appointmentTime)
    return date >= startDate && date <= endDate
  })
}

export const filterAppointmentsByPatient = (patientId: string): Appointment[] =>
  mockAppointments.filter(a => a.patientId === patientId)

export const filterAppointmentsByDentist = (dentistId: string): Appointment[] =>
  mockAppointments.filter(a => a.dentistId === dentistId)

// ─── Login mock ─────────────────────────────────────────────────────────────

const adminUser = mockUsers.find(u => u.role === 'ADMIN')!

export const mockLoginResponse: LoginResponse = {
  accessToken: 'demo-mock-token-clinical-atelier-2024',
  tokenType: 'Bearer',
  expiresIn: 86400,
  user: adminUser,
}

export const mockApiResponse = <T>(data: T): ApiResponse<T> => ({
  success: true,
  data,
  message: 'OK (demo mode)',
})

export const isDemoMode = (): boolean =>
  import.meta.env.VITE_DEMO_MODE === 'true'
